### ISSUE TITLE
⚠Неправильное поведение страницы после ввода неверных данных на A*

### ISSUE THREAD

**Issue by delet-dis** [Chantreck/ToxicCoders#10]
# 🐛 баг репорт
При отсутствии указания точек начала/конца выводится alert с ошибкой об их отсутствии, после его закрытия взаимодействие с интерактивными элементами становится невозможным, потому что не обновляется статус текущего действия 
# 🤔 ожидаемое поведение
Возможность указания отстуствующих данных сразу после закрытия alert'а
# 😮 текущее поведение
Невозможность нажатия на кнопочки сайдбара, полная смерть настроек до перезагрузки страницы
# 💁🏼‍♂️ возможное решение проблемы
Переезд на popups, который принесет лишь плюсы:
* Popups не будут блокировать браузер
* Не будут блокировать как UI,  так и javascript поток
* Через popup можно выводить все, что захочется, а не только строки
* Popup можно настроить так, чтобы он вылезал на определенное количество времени, с alert такую шалость осуществить нельзя
* Alert'ы могут быть заблокированы у конечного пользователя, что сразу сломает его UX

**Comment by Chantreck** [comment]
Спасибо за нахождение бага! Баг исправлен! 😍
